ДЗ5
vaganov-spb/2019-2-Track-Frontend-T-Vaganov pull request #15
Opened 2020-04-21 17:59 UTC by vaganov-spb

# Домашнее задание №
Прошу @martinkomitsky, @chexex или @priver проверить его.
Что было сделано:
Поддержка оффлайн
Собственная тема
Возможность установить на рабочий стол

2020-04-29 14:11 UTC, chexex reviewed
Прояснить положение с `Data` и `Date`

2020-04-29 14:11 UTC, chexex commented on .gitignore
> +src/pages/Chat_comp_useful.js
src/serviceModules/

и в serviceModules напихивай любые локальные модули для разработки

2020-04-29 14:11 UTC, chexex commented on .gitignore
> +backup.json
Это наталкивает на вопрос "а что может случится с package.json"? и, в конце-концов, ты ведь версионируешь package.json

2020-04-29 14:11 UTC, chexex commented on src/components/chatform/Input.js
> +				if(props.chatId === 'Group Chat') {
`if(props.ch...` – это точно так линтер пропустил?)

2020-04-29 14:11 UTC, chexex commented on src/pages/Chat.js
> +			const Data = JSON.parse(localStorage.getItem(chatId));
почему тайтлкейс? `const data`, может?) `Data` мешается с `Date` при беглом просмотре

2020-04-29 14:11 UTC, chexex commented on src/pages/Chat.js
> +								return <Message key={index} text={message.message} Date={(chatId !== 'Group Chat') ? message.time : moment(message.time).tz('Europe/Moscow').format('HH:mm')}/>;
в пропсах используется `Date`?)

2020-04-30 10:00 UTC, martinkomitsky commented
@vaganov-spb имеется конфликт, надо починить!

2020-05-07 06:09 UTC, chexex requested changes
комменты, конфликты

2020-05-18 11:49 UTC, closed without merging